### ISSUE TITLE
Native component for "RNSketch" does not exist

### ISSUE THREAD

**Issue by bec-smith** [jgrancher/react-native-sketch#36] opened 2017-11-13 05:16 UTC
Hi! I'm trying to test out RNS using Expo and used the following example code:
`
import React from 'react';
import { AppRegistry, Button, StyleSheet, View } from 'react-native';
import Sketch from 'react-native-sketch';

export default class LinksScreen extends React.Component {
  static navigationOptions = {
    title: 'Links',
  };

  clear = () => {
      this.sketch.clear();
    };

    save = () => {
      this.sketch.save().then(({ path }) => {
        console.log(`The image is saved there: ${path}`); // eslint-disable-line no-console
      });
    };

    render() {
      return (
        <View style={styles.container}>
          <Sketch
            ref={sketch => {
              this.sketch = sketch;
            }}
          />
          <View style={styles.actionsBar}>
            <Button color="#EA212E" onPress={this.clear} title="❌ Clear" />
            <Button color="#1DBD21" onPress={this.save} title="Save  ✅" />
          </View>
        </View>
      );
    }

}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#F5FCFF',
    flex: 1,
    paddingTop: 20,
  },
  actionsBar: {
    alignItems: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
});`

and this error got thrown:
`[exp] Warning: Native component for "RNSketch" does not exist
- node_modules/react-native/node_modules/fbjs/lib/warning.js:35:20 in printWarning
- node_modules/react-native/node_modules/fbjs/lib/warning.js:59:25 in warning
- node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:52:12 in requireNativeComponent
- node_modules/react-native-sketch/index.ios.js:75:40 in <unknown>
- node_modules/metro-bundler/src/Resolver/polyfills/require.js:178:12 in loadModuleImplementation
* screens/LinksScreen.js:3:0 in <unknown>
- node_modules/metro-bundler/src/Resolver/polyfills/require.js:178:12 in loadModuleImplementation
* navigation/MainTabNavigator.js:9:0 in <unknown>
- node_modules/metro-bundler/src/Resolver/polyfills/require.js:178:12 in loadModuleImplementation
* navigation/RootNavigation.js:5:0 in <unknown>
- node_modules/metro-bundler/src/Resolver/polyfills/require.js:178:12 in loadModuleImplementation
* App.js:5:0 in <unknown>
- node_modules/metro-bundler/src/Resolver/polyfills/require.js:178:12 in loadModuleImplementation
- node_modules/expo/AppEntry.js:2:0 in <unknown>
- ... 3 more stack frames from framework internals
`

**Comment by jgrancher** [comment] 2017-11-13 09:19
Hi @becnichelesmith. I think this issue is linked to Expo, so it'd be a duplicate of #35.

**Closed as completed by jgrancher** 2017-11-13 09:19 UTC
